In [3]:
import numpy as np

def generate_invertible_matrix(n):
    A = np.random.randint(1, 10, size=(n, n))

    while np.linalg.det(A) == 0:
        A = np.random.randint(1, 10, size=(n, n))

    return A

def generate_invertible_symmetric_matrix(n):
    B = np.random.randint(1, 10, size=(n, n))
    A = B + B.T
    while np.linalg.det(A) == 0:
        B = np.random.randint(1, 10, size=(n, n))
        A = B + B.T

    return A

def eigen_decomposition_and_reconstruction(A):
    eigenvalues, eigenvectors = np.linalg.eig(A)
    A_reconstructed = eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)
    return A_reconstructed

def check_reconstruction(A, A_reconstructed):
    reconstruction_error = np.linalg.norm(A - A_reconstructed)

    return reconstruction_error

SubTask 2A: Random Matrix (random_eigen.py)

In [4]:
n = int(input("Enter the dimension of the matrix (n): "))

A = generate_invertible_matrix(n)

A_reconstructed = eigen_decomposition_and_reconstruction(A)

reconstruction_error = check_reconstruction(A, A_reconstructed)

print("\nOriginal Matrix A:\n", A)
print("\nReconstructed Matrix A:\n", A_reconstructed)
print("\nReconstruction Error:", reconstruction_error)

if np.allclose(A, A_reconstructed):
    print("\nReconstruction is accurate.")
else:
    print("\nReconstruction is not accurate.")



Original Matrix A:
 [[7 9 8 8 3 5]
 [6 3 3 9 9 9]
 [4 5 7 7 1 4]
 [6 4 5 8 1 1]
 [3 7 8 8 3 6]
 [4 2 2 1 2 8]]

Reconstructed Matrix A:
 [[7.+1.12956597e-15j 9.+8.44775629e-17j 8.-5.37646604e-16j
  8.+1.75967466e-15j 3.+3.10669441e-16j 5.-6.05969236e-16j]
 [6.-6.49707464e-16j 3.-7.35364681e-16j 3.+4.78573331e-16j
  9.+2.75008031e-15j 9.+3.46738430e-16j 9.+1.63854392e-15j]
 [4.+1.27895262e-15j 5.+6.95090408e-17j 7.-4.62810056e-16j
  7.+1.24360542e-15j 1.+3.34265998e-17j 4.-7.26769408e-16j]
 [6.+1.36859866e-15j 4.-1.40780173e-18j 5.-2.04810886e-16j
  8.+1.17151469e-15j 1.-3.42012305e-16j 1.-4.41920383e-16j]
 [3.+1.10253597e-15j 7.-4.37245518e-17j 8.-4.43012967e-16j
  8.+1.75365302e-15j 3.+2.82048192e-16j 6.-4.71138293e-16j]
 [4.-4.16799503e-16j 2.+1.98609779e-17j 2.-2.06287729e-16j
  1.+6.39574206e-16j 2.+4.47382948e-16j 8.-1.81658205e-17j]]

Reconstruction Error: 3.7893727431799173e-14

Reconstruction is accurate.


SubTask 2B: Symmetric Matrix (symmetric_eigen.py)




In [5]:
n = int(input("Enter the dimension of the matrix (n): "))

A = generate_invertible_symmetric_matrix(n)

A_reconstructed = eigen_decomposition_and_reconstruction(A)

# Check if the reconstruction is accurate
reconstruction_error = check_reconstruction(A, A_reconstructed)

# Print the results
print("\nOriginal Matrix A:\n", A)
print("\nReconstructed Matrix A:\n", A_reconstructed)
print("\nReconstruction Error:", reconstruction_error)

# Check if the reconstruction is close to the original matrix
if np.allclose(A, A_reconstructed):
    print("\nReconstruction is accurate.")
else:
    print("\nReconstruction is not accurate.")



Original Matrix A:
 [[ 4 12  9 11 11 10  8]
 [12 18  5 13 11 10 11]
 [ 9  5 14 12 12  8 13]
 [11 13 12  8 13 10 11]
 [11 11 12 13 14 17  4]
 [10 10  8 10 17  8  5]
 [ 8 11 13 11  4  5 12]]

Reconstructed Matrix A:
 [[ 4. 12.  9. 11. 11. 10.  8.]
 [12. 18.  5. 13. 11. 10. 11.]
 [ 9.  5. 14. 12. 12.  8. 13.]
 [11. 13. 12.  8. 13. 10. 11.]
 [11. 11. 12. 13. 14. 17.  4.]
 [10. 10.  8. 10. 17.  8.  5.]
 [ 8. 11. 13. 11.  4.  5. 12.]]

Reconstruction Error: 1.9368399904710765e-13

Reconstruction is accurate.
