In [144]:
from NN import *

Import Dataset

In [145]:
from torchvision import datasets, transforms 

train_validation_dataset = datasets.EMNIST(root='./data', 
                                           split='letters',
                                           train=True,
                                           transform=transforms.ToTensor(),
                                           download=True,
                                        )


independent_test_dataset = datasets.EMNIST(
                             root='./data',
                             split='letters',
                             train=False,
                             transform=transforms.ToTensor(),
                             )


In [146]:
type(train_validation_dataset)
n_classes = len(train_validation_dataset.classes)
n_datapoints = len(train_validation_dataset.targets)

X_train = np.array(train_validation_dataset.data.reshape(-1,28*28))
# y_train = np.zeros((len(train_validation_dataset.targets),len(train_validation_dataset.classes)))

y_train = np.array([[1 if temp == i else 0 for i in range(n_classes)] for temp in train_validation_dataset.targets])
y_train[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [147]:
X_test = np.array(independent_test_dataset.data.reshape(-1,28*28))
y_test = np.array([[1 if temp == i else 0 for i in range(n_classes)] for temp in independent_test_dataset.targets])

In [148]:
import pandas as pd 

df = pd.DataFrame(train_validation_dataset.data.reshape(-1,28*28))

In [149]:
model = NN(Linear(28*28,1024), ReLU(), Dropout(0.2), Linear(1024,n_classes), ReLU(), Dropout(0.3), Softmax())

In [182]:
model.train(cross_entropy, cross_entropy_grad, X_train, y_train, batch_size=2048, epochs=100, learning_rate=0.01)

epoch=0, error=0.09682987462622586
epoch=1, error=0.08979564578590082
epoch=2, error=0.08703034864584613
epoch=3, error=0.08439715070249837
epoch=4, error=0.08301133318786054
epoch=5, error=0.08111321588044149
epoch=6, error=0.07969134056433028
epoch=7, error=0.07818273685001768
epoch=8, error=0.0774407957545969
epoch=9, error=0.07643887129417969
epoch=10, error=0.07562021819976357
epoch=11, error=0.07467474413936605
epoch=12, error=0.07404767234216798
epoch=13, error=0.07368855045625104
epoch=14, error=0.073099145226264
epoch=15, error=0.0723291389719758
epoch=16, error=0.07155675455307398
epoch=17, error=0.07139172252777062
epoch=18, error=0.0708584399788763
epoch=19, error=0.07028728997060513
epoch=20, error=0.06993349370147545
epoch=21, error=0.06915493943393164
epoch=22, error=0.06891775517307658
epoch=23, error=0.06862705494170196
epoch=24, error=0.06819136415518565
epoch=25, error=0.06755214597528371
epoch=26, error=0.06719381400733344
epoch=27, error=0.06680808193846759
epoch=2

In [183]:
model.save("model1024_2.pkl")

In [184]:
model.eval(X_test,y_test,batch_size=2048)

0.5991346153846154

In [185]:
id = np.random.randint(0,len(X_train))
x_ = X_train[id:id+1].T 
y_ = y_train[id:id+1].T 

print(model(x_))


[[2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [9.01907102e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [1.00000000e+00]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]
 [2.53851840e-18]]


In [186]:
print(y_)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [187]:
np.argmax(model(x_),axis=0) == np.argmax(y_,axis=0)

array([ True])