In [1]:
from NN import *

Import Dataset

In [2]:
from torchvision import datasets, transforms 

train_validation_dataset = datasets.EMNIST(root='./data', 
                                           split='letters',
                                           train=True,
                                           transform=transforms.ToTensor(),
                                           download=True,
                                        )


independent_test_dataset = datasets.EMNIST(
                             root='./data',
                             split='letters',
                             train=False,
                             transform=transforms.ToTensor(),
                             )


In [6]:
type(train_validation_dataset)
n_classes = len(train_validation_dataset.classes)-1
n_datapoints = len(train_validation_dataset.targets)

X_train = np.array(train_validation_dataset.data.reshape(-1,28*28))
y_train = np.array([[1 if temp == i+1 else 0 for i in range(n_classes)] for temp in train_validation_dataset.targets])

In [7]:
X_test = np.array(independent_test_dataset.data.reshape(-1,28*28))
y_test = np.array([[1 if temp == i+1 else 0 for i in range(n_classes)] for temp in independent_test_dataset.targets])

In [8]:
#standard scaler 
X_mean = np.mean(X_train,axis=0, keepdims=True)
X_std = np.std(X_train,axis=0,keepdims=True)
eps = 1e-8
X_train = (X_train-X_mean)/(X_std + eps)
X_test = (X_test-X_mean)/(X_std + eps)

In [10]:
X_train[:3].max()

8.924607691004123

In [13]:
model = NN(Linear(28*28,1024), ReLU(), Dropout(0.3), Linear(1024,n_classes), Softmax())

In [14]:
model.train(cross_entropy, cross_entropy_grad, X_train, y_train, batch_size=2048, epochs=20, learning_rate=5e-3)

epoch=0, train_loss=0.040649536751499314, val_loss=0.28650016981017495
epoch=1, train_loss=0.02125051394159884, val_loss=0.2406460997540334
epoch=2, train_loss=0.01740479895874721, val_loss=0.21822938285202229
epoch=3, train_loss=0.015764998640813474, val_loss=0.20650813854933106
epoch=4, train_loss=0.014525941168237721, val_loss=0.20002857787209027
epoch=5, train_loss=0.013825759564330475, val_loss=0.19733450830620775
epoch=6, train_loss=0.013076719347912769, val_loss=0.19066111364200244
epoch=7, train_loss=0.012265480768381049, val_loss=0.1816938258686882
epoch=8, train_loss=0.011436823678123346, val_loss=0.17606353368921718
epoch=9, train_loss=0.01088762851238487, val_loss=0.17583673954567378
epoch=10, train_loss=0.010136496951166137, val_loss=0.17262139046066735
epoch=11, train_loss=0.009576476618350725, val_loss=0.16653286839609266
epoch=12, train_loss=0.008875842679812002, val_loss=0.16745421028349866
epoch=13, train_loss=0.008453303351934782, val_loss=0.16460947016183505
epoch=1

In [24]:
model.save("model1024_3.pkl")

In [20]:
model.eval(X_train,y_train,batch_size=2048)

0.9555288461538461

In [21]:
id = np.random.randint(0,len(X_train))
x_ = X_train[id:id+1].T 
y_ = y_train[id:id+1].T 

print(model(x_))


[[4.45116634e-06]
 [4.53162807e-06]
 [3.53553076e-07]
 [8.59187604e-07]
 [9.99004249e-01]
 [1.99136923e-08]
 [6.43115465e-09]
 [1.03401883e-07]
 [8.26942614e-11]
 [1.06527418e-10]
 [2.68772884e-05]
 [1.48437765e-11]
 [2.87164102e-10]
 [1.36284963e-07]
 [8.14943406e-09]
 [4.77140150e-07]
 [7.34469979e-11]
 [5.03884495e-05]
 [3.31194223e-11]
 [8.66284492e-04]
 [1.05180796e-07]
 [1.33072448e-08]
 [1.52332377e-10]
 [4.13690038e-07]
 [2.91189439e-09]
 [4.07180334e-05]]


In [22]:
print(y_)

[[0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [23]:
np.argmax(model(x_),axis=0) == np.argmax(y_,axis=0)

array([ True])