In [17]:
from NN import *

Import Dataset

In [18]:
from torchvision import datasets, transforms 

train_validation_dataset = datasets.EMNIST(root='./data', 
                                           split='letters',
                                           train=True,
                                           transform=transforms.ToTensor(),
                                           download=True,
                                        )


independent_test_dataset = datasets.EMNIST(
                             root='./data',
                             split='letters',
                             train=False,
                             transform=transforms.ToTensor(),
                             )


In [19]:
type(train_validation_dataset)
n_classes = len(train_validation_dataset.classes)
n_datapoints = len(train_validation_dataset.targets)

X_train = np.array(train_validation_dataset.data.reshape(-1,28*28))
# y_train = np.zeros((len(train_validation_dataset.targets),len(train_validation_dataset.classes)))

y_train = np.array([[1 if temp == i else 0 for i in range(n_classes)] for temp in train_validation_dataset.targets])
y_train[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [20]:
X_test = np.array(independent_test_dataset.data.reshape(-1,28*28))
y_test = np.array([[1 if temp == i else 0 for i in range(n_classes)] for temp in independent_test_dataset.targets])

In [21]:
model = NN(Linear(28*28,1024), ReLU(), Dropout(0.3), Linear(1024,n_classes), Softmax())

In [58]:
model.train(cross_entropy, cross_entropy_grad, X_train, y_train, batch_size=2048, epochs=20, learning_rate=5e-5)

epoch=0, error=0.19611174422148434
epoch=1, error=0.19474451111507196
epoch=2, error=0.1953931756555599
epoch=3, error=0.19453829603258305
epoch=4, error=0.19323317781438656
epoch=5, error=0.1934014998515111
epoch=6, error=0.1930817542427191
epoch=7, error=0.191863355025612
epoch=8, error=0.19118358189114698
epoch=9, error=0.19119868377571128
epoch=10, error=0.18985371694633568
epoch=11, error=0.19022677589839546
epoch=12, error=0.1888674568636171
epoch=13, error=0.18765067672193855
epoch=14, error=0.18799045635915057
epoch=15, error=0.18620994041905856
epoch=16, error=0.18733872358860224
epoch=17, error=0.18648722074517024
epoch=18, error=0.1860709377376707
epoch=19, error=0.18564915185662073


In [60]:
model.save("model1024.pkl")

In [59]:
model.eval(X_test,y_test,batch_size=2048)

0.8103846153846154

In [32]:
id = np.random.randint(0,len(X_train))
x_ = X_train[id:id+1].T 
y_ = y_train[id:id+1].T 

print(model(x_))


[[3.63504985e-41]
 [5.77990454e-21]
 [9.95595662e-01]
 [2.28029202e-85]
 [3.04202706e-47]
 [4.35476633e-29]
 [3.04825815e-47]
 [8.14499471e-34]
 [5.23722602e-05]
 [3.65418240e-82]
 [9.21607136e-87]
 [2.62560943e-06]
 [6.92068895e-65]
 [1.10347200e-04]
 [3.50207296e-13]
 [8.64525089e-50]
 [5.83147546e-52]
 [7.12789115e-74]
 [2.08957650e-18]
 [5.42879484e-70]
 [8.02427850e-34]
 [1.82240026e-32]
 [1.77256754e-34]
 [9.00278927e-37]
 [1.65306472e-11]
 [9.01058694e-39]
 [4.23899303e-03]]


In [33]:
print(y_)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [34]:
np.argmax(model(x_),axis=0) == np.argmax(y_,axis=0)

array([False])