In [68]:
import numpy as np
rand = np.random.default_rng(42)

In [69]:
class Layer:
    def __init__(self):
        pass 

    def __call__(self,x,train=False):
        pass 

    def backward(self,out_grad,learning_rate):
        pass 

In [70]:
class Linear(Layer):
    def __init__(self,fan_in,fan_out,seed=42):
        self.fan_in = fan_in 
        self.fan_out = fan_out

        #xavier init 
        limit = np.sqrt(6 / (fan_in + fan_out))
        self.weights = np.random.uniform(-limit, limit, size=(fan_out, fan_in))
        self.bias = np.ones((fan_out,1))

    def __call__(self,x,train=False):
        self.input = x
        return np.dot(self.weights,self.input) + self.bias
    

    def __repr__(self):
        pass 

    def backward(self, out_grad, learning_rate ):
        wgrad = np.dot(out_grad, self.input.T) / np.size(out_grad, axis=1) # mean  
        bgrad = np.mean(out_grad, axis=1, keepdims=True) 
        inputgrad = np.dot(self.weights.T, out_grad)

        self.weights -= learning_rate * wgrad 
        self.bias -= learning_rate * bgrad 

        # print(f"{self.wgrad}")
        # print(f"{self.bgrad}")

        return inputgrad 

    def reset_grad(self):
        self.wgrad = np.zeros((self.fan_in,self.fan_out))
        self.bgrad = np.zeros((1,self.fan_out)) 


In [71]:
class Softmax(Layer):
    def __call__(self, input, train=False):
        self.input = input
        tmp = input - np.max(input, axis=0)  
        tmp = np.exp(tmp)
        self.output = tmp / np.sum(tmp, axis=0, keepdims=True)
        return self.output 
    def backward(self, out_grad, learning_rate):
        assert out_grad.shape == self.input.shape
        n = np.size(self.output, axis=0) 
        # grad = np.hstack([ np.dot( (np.identity(n) - input )*input.T, out_grad) for input in self.input.T  ])
        # grad = np.hstack([np.dot( (np.identity(n) - self.input[:,i:i+1].T)*self.input[:,i:i+1], out_grad[:,i:i+1] ) for i in range(np.size(self.input,axis=1)) ])
         # Modify the backward calculation for improved numerical stability
        grad = np.hstack([
            np.dot( (np.identity(n) - self.output[:, i:i+1].T) * self.output[:, i:i+1] , out_grad[:, i:i+1])
            for i in range(np.size(self.input, axis=1))
        ])
        
        return grad #np.dot((np.identity(n)-self.output.T) * self.output, out_grad)  

In [72]:
class Activation(Layer):
    def __init__(self,activation,activation_prime):
        self.activation = activation 
        self.activation_grad = activation_prime

    def __call__(self, input, train=False):
        self.input = input 
        return self.activation(self.input) 
    
    def backward(self, out_grad, learning_rate):
        return np.multiply(out_grad, self.activation_grad(self.input))

In [73]:
class Tanh(Activation):
    def __init__(self):
        def tanh(x):
            return np.tanh(x)
        def tanh_grad(x):
            return 1-np.tanh(x)**2 
        super().__init__(tanh,tanh_grad)

In [74]:
class Sigmoid(Activation):
    def __init__(self):
        def sigmoid(x):
            return 1.0 / (1.0 + np.exp(-x))
        
        def sigmoid_grad(x):
            return sigmoid(x) * (1.0 - sigmoid(x)) 
        super().__init__(sigmoid,sigmoid_grad) 
            

In [75]:
class ReLU(Activation):
    def __init__(self):
        def relu(x):
            return np.maximum(0,x)
        def relu_grad(x):
            return np.where(x > 0, 1, np.where(x < 0, 0, 0.5))
        super().__init__(relu,relu_grad)

In [76]:
class Dropout(Layer):
    def __init__(self, dropout_rate):
        self.dropout_rate = dropout_rate
        self.mask = None

    def __call__(self, x, train=False):
        if train:
            self.mask = (np.random.rand(*x.shape) < (1 - self.dropout_rate)) / (1 - self.dropout_rate)
            # print(self.mask)
            return x * self.mask
        else:
            return x

    def backward(self, grad, learning_rate):
        return grad * self.mask if self.mask is not None else grad

In [77]:
def mse(y_true, y_pred):
    return np.mean(np.power(y_true - y_pred, 2))

def mse_grad(y_true, y_pred):
    return 2 * (y_pred - y_true) / np.size(y_true)

def binary_cross_entropy(y_true, y_pred):
    return np.mean(-y_true * np.log(y_pred) - (1 - y_true) * np.log(1 - y_pred))

def binary_cross_entropy_grad(y_true, y_pred): # wrt y_pred
    return ((1 - y_true) / (1 - y_pred) - y_true / y_pred) / np.size(y_true)

def cross_entropy(y_true,y_pred,epsilon=1e-15):
    y_pred = np.clip( y_pred, epsilon, 1.0-epsilon)
    return np.mean(-y_true*np.log(y_pred)) 

def cross_entropy_grad(y_true,y_pred,epsilon=1e-15):
    y_pred = np.clip( y_pred, epsilon, 1.0-epsilon)
    return (-y_true/y_pred) / len(y_true)  

In [78]:
class NN:
    def __init__(self, *layers):
        self.layers : Layer = [] 
        for layer in layers:
            self.layers += [layer]
        
    def __call__(self,input,train=False):
        for layer in self.layers:
            input = layer(input,train=train)
        return input 
    def backward(self, ):
        pass 
    
    def save(self,filename):
        pass 
    def load(self,filename):
        pass
    
    def train_minibatch(self,):
        pass 
    
    def train(self, loss, loss_grad, X, y, epochs = 1000, batch_size = 8, learning_rate = 0.001, verbose=True):
        shuffled_indices = np.arange(len(X))
        np.random.shuffle(shuffled_indices) 

        X = X[shuffled_indices]
        y = y[shuffled_indices] 

        for epoch in range(epochs):
            error = 0 

            for i in range((len(X)+batch_size-1)//batch_size):
                X_batch = X[i:i+batch_size].T
                y_batch = y[i:i+batch_size].T

                y_pred = self.__call__(X_batch,train=True)
                error += loss(y_batch,y_pred)

                grad = loss_grad(y_batch,y_pred)

                for layer in reversed(self.layers):
                    grad = layer.backward(grad, learning_rate)
            error /= len(X)
            if verbose:
                print(f"{epoch=}, {error=}")

    def eval(self, X,y,batch_size=1):
        corr = 0 
        for i in range((len(X)+batch_size-1)//batch_size):
            x_ = X[i:i+batch_size].T
            y_ = y[i:i+batch_size].T

            y_pred = self.__call__(x_)
            corr += np.sum(np.argmax(y_pred,axis=0) == np.argmax(y_,axis=0)) 
        # for x,y in zip(X,y):
        #     y_pred = self.__call__(x)
        #     corr += 1 if np.argmax(y_pred) == np.argmax(y) else 0 
        
        return corr/len(X) 
    


Import Dataset

In [79]:
from torchvision import datasets, transforms 

train_validation_dataset = datasets.EMNIST(root='./data', 
                                           split='letters',
                                           train=True,
                                           transform=transforms.ToTensor(),
                                           download=True,
                                        )


independent_test_dataset = datasets.EMNIST(
                             root='./data',
                             split='letters',
                             train=False,
                             transform=transforms.ToTensor(),
                             )


In [80]:
type(train_validation_dataset)
n_classes = len(train_validation_dataset.classes)
n_datapoints = len(train_validation_dataset.targets)

X_train = np.array(train_validation_dataset.data.reshape(-1,28*28))
# y_train = np.zeros((len(train_validation_dataset.targets),len(train_validation_dataset.classes)))

y_train = np.array([[1 if temp == i else 0 for i in range(n_classes)] for temp in train_validation_dataset.targets])
y_train[3]

In [ ]:
X_test = np.array(independent_test_dataset.data.reshape(-1,28*28))
y_test = np.array([[1 if temp == i else 0 for i in range(n_classes)] for temp in independent_test_dataset.targets])

In [ ]:
import pandas as pd 

df = pd.DataFrame(train_validation_dataset.data.reshape(-1,28*28))

In [ ]:
model = NN(Linear(28*28,1024), ReLU(), Dropout(0.2), Linear(1024,n_classes), ReLU(), Dropout(0.3), Softmax())

In [ ]:
model.train(cross_entropy, cross_entropy_grad, X_train, y_train, batch_size=1000, epochs=10, learning_rate=0.01)

epoch=0, error=0.0007381103103949528
epoch=1, error=0.000678122593170925
epoch=2, error=0.00064978466160602
epoch=3, error=0.0006267066699037875
epoch=4, error=0.0006091351636172451
epoch=5, error=0.0005791872130125389
epoch=6, error=0.0005456173984648285
epoch=7, error=0.000517134436461047
epoch=8, error=0.0004914480621761369
epoch=9, error=0.0004750115577888625


In [ ]:
model.eval(X_test,y_test,batch_size=1000)

TypeError: NN.eval() got an unexpected keyword argument 'batch_size'

In [ ]:
model(X_train[:1].T)

array([[1.41539858e-96],
       [9.99999818e-01],
       [9.07056237e-85],
       [1.41539858e-96],
       [1.41539858e-96],
       [9.13389696e-53],
       [1.41539858e-96],
       [4.95680781e-81],
       [3.04989874e-93],
       [1.41539858e-96],
       [7.06031606e-95],
       [3.82759760e-73],
       [1.41539858e-96],
       [4.06226150e-54],
       [2.08611634e-77],
       [1.13342514e-85],
       [1.37054920e-94],
       [1.41539858e-96],
       [1.82255865e-07],
       [1.41539858e-96],
       [2.81511746e-37],
       [1.91337008e-71],
       [1.41539858e-96],
       [1.41539858e-96],
       [1.41539858e-96],
       [2.89750881e-52],
       [1.55141873e-77]])

In [ ]:
y_train[:1].T

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0]])

In [ ]:
sf = Softmax()

In [ ]:
x = np.array([[1,2,3] for _ in range(4)])

In [ ]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
sf(x)

array([[0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25]])