In [133]:
from NN import *

Import Dataset

In [134]:
from torchvision import datasets, transforms 

train_validation_dataset = datasets.EMNIST(root='./data', 
                                           split='letters',
                                           train=True,
                                           transform=transforms.ToTensor(),
                                           download=True,
                                        )


independent_test_dataset = datasets.EMNIST(
                             root='./data',
                             split='letters',
                             train=False,
                             transform=transforms.ToTensor(),
                             )


In [135]:
type(train_validation_dataset)
n_classes = len(train_validation_dataset.classes)
n_datapoints = len(train_validation_dataset.targets)

X_train = np.array(train_validation_dataset.data.reshape(-1,28*28))
# y_train = np.zeros((len(train_validation_dataset.targets),len(train_validation_dataset.classes)))

y_train = np.array([[1 if temp == i else 0 for i in range(n_classes)] for temp in train_validation_dataset.targets])
y_train[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [136]:
X_test = np.array(independent_test_dataset.data.reshape(-1,28*28))
y_test = np.array([[1 if temp == i else 0 for i in range(n_classes)] for temp in independent_test_dataset.targets])

In [137]:
import pandas as pd 

df = pd.DataFrame(train_validation_dataset.data.reshape(-1,28*28))

In [138]:
model = NN(Linear(28*28,1024), ReLU(), Dropout(0.2), Linear(1024,n_classes), ReLU(), Dropout(0.3), Softmax())

In [139]:
model.train(cross_entropy, cross_entropy_grad, X_train, y_train, batch_size=2048, epochs=30, learning_rate=0.01)

epoch=0, error=0.0005741746373005041
epoch=1, error=0.0005409113088852629
epoch=2, error=0.0005031785775805348
epoch=3, error=0.0004728166942663148
epoch=4, error=0.0004494067597583026
epoch=5, error=0.00043422715339249974
epoch=6, error=0.00042519746255231626
epoch=7, error=0.00041712359369314677
epoch=8, error=0.000409647299436343
epoch=9, error=0.00040314309158659265
epoch=10, error=0.00039692084837879434
epoch=11, error=0.00038650761974601337
epoch=12, error=0.0003732078752581379
epoch=13, error=0.00036271208852709386
epoch=14, error=0.00035396930328336927
epoch=15, error=0.00034778812810036655
epoch=16, error=0.00034002710681876137
epoch=17, error=0.0003326872631445225
epoch=18, error=0.00032342723067346947
epoch=19, error=0.00031559285756785365


AttributeError: Can't pickle local object 'ReLU.__init__.<locals>.relu'

In [ ]:
model.save("model1024_2.pkl")

In [140]:
model.eval(X_test,y_test,batch_size=2048)

0.44067307692307695

In [141]:
id = np.random.randint(0,len(X_train))

print(model(X_train[id:id+1].T))


[[7.91408792e-80]
 [1.05365609e-52]
 [2.22659037e-83]
 [3.82785974e-84]
 [3.82785974e-84]
 [3.82785974e-84]
 [5.16329357e-75]
 [1.21035716e-82]
 [7.52227960e-67]
 [4.76341874e-32]
 [3.97117370e-50]
 [3.82785974e-84]
 [1.00000000e+00]
 [3.82785974e-84]
 [3.82785974e-84]
 [2.41969837e-82]
 [3.82785974e-84]
 [2.10902653e-57]
 [3.82785974e-84]
 [1.70189189e-72]
 [1.14537175e-46]
 [3.82785974e-84]
 [3.82785974e-84]
 [3.82785974e-84]
 [2.19413041e-79]
 [2.46409270e-69]
 [1.49049135e-75]]


In [142]:
print(y_train[id:id+1].T)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
