In [2]:
import numpy as np
rand = np.random.default_rng(42)

In [3]:
class Linear:
    def __init__(self,fan_in,fan_out,seed=42):
        self.fan_in = fan_in 
        self.fan_out = fan_out
        self.rand = np.random.default_rng(seed)
        self.weights = self.rand.random((fan_in,fan_out))
        self.bias = np.ones((1,fan_out))
        self.grad = np.zeros((fan_in,fan_out))

        # print(self.weights.shape)
        # print(self.grad.shape)
    def __call__(self,x):
        return np.dot(x.reshape((-1,self.fan_in)),self.weights) + self.bias
    def __repr__(self):
        pass 

In [4]:
class ReLU:
    def __init__(self,fan_in,seed=42):
        self.fan_in = fan_in 
        
    def __call__(self,x):
        return np.maximum(x,0)
    def __repr__(self):
        pass 

In [5]:
class Sigmoid:
    def __init__(self,fan_in,seed=42):
        self.fan_in=fan_in 

    def __call__(self,x):
        return 1.0/(1.0+np.exp(-x))
    
    def __repr__(self):
        pass

In [6]:
lin = Linear(10,5)
relu = ReLU(5) 
sigmoid = Sigmoid(5)

model = [lin, sigmoid, relu] 

x = rand.random(10)

print(x)
for layer in model:
    x = layer(x) 
    print(x)

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735 0.97562235
 0.7611397  0.78606431 0.12811363 0.45038594]
[[3.89957597 4.46464935 3.5824885  3.92192523 3.88495561]]
[[0.98015145 0.98862221 0.97294586 0.98058161 0.97986501]]
[[0.98015145 0.98862221 0.97294586 0.98058161 0.97986501]]


In [14]:
res = input.reshape((-1,1))*w

res.shape

(32, 10)

In [ ]:
sdfhasdfsdf