In [1]:
import numpy as np

In [2]:
def mse(y_true, y_pred):
    return np.mean(np.power(y_true - y_pred, 2))

def mse_grad(y_true, y_pred):
    return 2 * (y_pred - y_true) / np.size(y_true)

def binary_cross_entropy(y_true, y_pred):
    return np.mean(-y_true * np.log(y_pred) - (1 - y_true) * np.log(1 - y_pred))

def binary_cross_entropy_grad(y_true, y_pred): # wrt y_pred
    return ((1 - y_true) / (1 - y_pred) - y_true / y_pred) / np.size(y_true)

def cross_entropy(y_true,y_pred,epsilon=1e-15):
    y_pred = np.clip(y_pred, epsilon, 1.0-epsilon)
    return np.mean(-y_true*np.log(y_pred)) 

def cross_entropy_grad(y_true,y_pred,epsilon=1e-15):
    y_pred = np.clip(y_pred, epsilon, 1.0-epsilon)
    return np.mean(-y_true/y_pred) 

In [3]:
y_pred = np.random.randn(4,3)
y_pred = np.exp(y_pred)/np.sum( np.exp(y_pred),axis=0) 
y_pred

array([[0.44985335, 0.47538224, 0.18754413],
       [0.44573357, 0.12604105, 0.54536274],
       [0.01293806, 0.13508158, 0.06646485],
       [0.09147502, 0.26349513, 0.20062828]])

In [4]:
y = np.array( [np.random.randint(0,4) for i in range(3)] )
y
y = np.array([[1 if val==i else 0 for i in range(4)] for val in y]).T
y

array([[1, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
np.sum(np.argmax(y_pred,axis=0) == np.argmax(y,axis=0))

3

In [6]:
cross_entropy_grad(y,y_pred)

-0.5133465799808925

In [7]:
import numpy as np

def cross_entropy_loss(y_true, y_pred):
    """
    Calculate the cross-entropy loss.

    Parameters:
    - y_true: 2D array with one-hot encoded true class labels (shape: [num_samples, num_classes]).
    - y_pred: 2D array with predicted probabilities (shape: [num_samples, num_classes]).

    Returns:
    - float: Cross-entropy loss.
    """
    epsilon = 1e-15  # Small constant to avoid log(0)
    num_samples = len(y_true)

    # Clip predicted probabilities to avoid log(0)
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)

    # Calculate cross-entropy loss
    loss = -np.sum(y_true * np.log(y_pred)) / num_samples
    return loss

def cross_entropy_loss_grad(y_true, y_pred):
    """
    Calculate the gradient of the cross-entropy loss with respect to the predicted probabilities.

    Parameters:
    - y_true: 2D array with one-hot encoded true class labels (shape: [num_samples, num_classes]).
    - y_pred: 2D array with predicted probabilities (shape: [num_samples, num_classes]).

    Returns:
    - 2D array: Gradient of the cross-entropy loss with respect to y_pred (shape: [num_samples, num_classes]).
    """
    epsilon = 1e-15  # Small constant to avoid division by zero
    num_samples = len(y_true)

    # Clip predicted probabilities to avoid division by zero
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)

    # Calculate the gradient of the cross-entropy loss
    grad = (-y_true / y_pred) / num_samples
    return grad

# Example usage
num_classes = 3
num_samples = 5

# Generate random one-hot encoded true labels and predicted probabilities
y_true = np.eye(num_classes)[np.random.choice(num_classes, num_samples)]
y_pred = np.random.rand(num_samples, num_classes)

# Calculate cross-entropy loss
loss = cross_entropy_loss(y_true, y_pred)
print(f"Cross-entropy loss: {loss:.4f}")

# Calculate the gradient of cross-entropy loss
grad = cross_entropy_loss_grad(y_true, y_pred)
print("Gradient of cross-entropy loss:")
print(grad)


Cross-entropy loss: 1.1553
Gradient of cross-entropy loss:
[[-0.         -0.         -0.47272735]
 [-0.         -3.49311541 -0.        ]
 [-0.86580484 -0.         -0.        ]
 [-0.29518879 -0.         -0.        ]
 [-0.         -0.24468455 -0.        ]]


In [8]:
y = [2,3, 4]

np.argmax(y)

2

In [9]:
y = np.array([i for i in range(16)])

In [10]:
y.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [11]:
import numpy as np

# Example arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array(['a', 'b', 'c', 'd', 'e'])

# Generate shuffled indices
shuffled_indices = np.arange(len(array1))
np.random.shuffle(shuffled_indices)

# Shuffle both arrays using the same indices
shuffled_array1 = array1[shuffled_indices]
shuffled_array2 = array2[shuffled_indices]

# Print the original and shuffled arrays
print("Original array1:", array1)
print("Original array2:", array2)
print("\nShuffled array1:", shuffled_array1)
print("Shuffled array2:", shuffled_array2)


Original array1: [1 2 3 4 5]
Original array2: ['a' 'b' 'c' 'd' 'e']

Shuffled array1: [2 3 4 5 1]
Shuffled array2: ['b' 'c' 'd' 'e' 'a']


In [12]:
xx = (np.arange(10))
np.random.shuffle(xx)
xx

array([1, 0, 7, 5, 9, 4, 8, 2, 6, 3])

In [13]:
xx[:4]

array([1, 0, 7, 5])

In [14]:
xx[4:8]

array([9, 4, 8, 2])

In [15]:
xx[8:12]

array([6, 3])

In [16]:
8/3

2.6666666666666665

In [17]:
8//3

2

In [18]:
batch_size = 8
(17+batch_size-1)//batch_size

3

In [19]:
x = np.array([_ for _ in range(16)]).reshape(4,4)

In [20]:
x = x.reshape(4,2,2)
x

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [21]:
for i in range(3):
    print(np.sum(x, axis=i))
    print()

[[24 28]
 [32 36]]

[[ 2  4]
 [10 12]
 [18 20]
 [26 28]]

[[ 1  5]
 [ 9 13]
 [17 21]
 [25 29]]



In [22]:
x = np.arange(16).reshape(-1,2)

In [23]:
np.size(x, axis=1)

2

In [24]:
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [25]:
np.mean(x, axis=1, keepdims=True)

array([[ 0.5],
       [ 2.5],
       [ 4.5],
       [ 6.5],
       [ 8.5],
       [10.5],
       [12.5],
       [14.5]])

In [26]:
x = x-np.max(x,axis=0)
x

array([[-14, -14],
       [-12, -12],
       [-10, -10],
       [ -8,  -8],
       [ -6,  -6],
       [ -4,  -4],
       [ -2,  -2],
       [  0,   0]])

In [27]:
x = np.exp(x) / np.sum( np.exp(x), axis=0, keepdims=True)
x

array([[7.18993625e-07, 7.18993625e-07],
       [5.31268423e-06, 5.31268423e-06],
       [3.92557218e-05, 3.92557218e-05],
       [2.90062731e-04, 2.90062731e-04],
       [2.14328979e-03, 2.14328979e-03],
       [1.58368885e-02, 1.58368885e-02],
       [1.17019658e-01, 1.17019658e-01],
       [8.64664814e-01, 8.64664814e-01]])

In [28]:
np.sum(x, axis=0,keepdims=True)

array([[1., 1.]])

In [29]:
x = np.arange(12).reshape(4,3)

In [30]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
out_grad = np.random.randn(4,3)
out_grad

array([[-0.41885088, -0.96845476,  0.19428307],
       [ 1.26104745,  0.44961784,  0.37241741],
       [ 1.56903017, -1.37990388, -0.97286369],
       [ 1.04896944, -0.83425423, -0.5863052 ]])

In [32]:
out_grad[:,1:2]

array([[-0.96845476],
       [ 0.44961784],
       [-1.37990388],
       [-0.83425423]])

In [33]:
n = np.size(x,axis=0)

In [34]:
index = 2
input = x[:,index:index+1]
print(f"{input}")
print(f"{out_grad[:,index:index+1]}")
np.dot( (np.identity(n) - input.T )*input, out_grad[:,index:index+1]) 

[[ 2]
 [ 5]
 [ 8]
 [11]]
[[ 0.19428307]
 [ 0.37241741]
 [-0.97286369]
 [-0.5863052 ]]


array([[ 24.35179321],
       [ 61.77015472],
       [ 88.06999876],
       [125.34839167]])

In [35]:
np.size(x, axis=1) == np.size(out_grad, axis=1)

True

In [36]:
print(np.hstack( [np.dot( (np.identity(n)-x[:,i:i+1].T)*x[:,i:i+1], out_grad[:,i:i+1]) for i in range(np.size(x,axis=1)) ] ))
print()
print(np.hstack( [[np.dot( (np.identity(n)-x[:,i:i+1].T)*x[:,i:i+1], out_grad[:,i:i+1])] for i in range(np.size(x,axis=1)) ] ))


[[   0.           16.20339809   24.35179321]
 [ -64.13100273   70.48588277   61.77015472]
 [-126.4141091   110.54364283   88.06999876]
 [-194.3017102   163.37598624  125.34839167]]

[[[   0.        ]
  [ -64.13100273]
  [-126.4141091 ]
  [-194.3017102 ]
  [  16.20339809]
  [  70.48588277]
  [ 110.54364283]
  [ 163.37598624]
  [  24.35179321]
  [  61.77015472]
  [  88.06999876]
  [ 125.34839167]]]


In [37]:
grad = np.hstack([ np.dot( (np.identity(n) - input.T )*input, og.T) for input,og in zip(x.T, out_grad.T)  ])

In [38]:
grad

array([-152.80103808, -149.01789574, -143.38685705, -143.36031309,
        143.84682763,  146.61375374,  135.15595524,  136.47274009,
        123.50720404,  124.98072495,  115.33572839,  116.66928069])

In [39]:
input = x.T[2]


In [40]:


z = np.random.randn(4,3)

In [41]:
z

array([[-0.10317307, -2.13853605,  0.82948688],
       [-1.00906227, -0.44969504,  1.75406701],
       [-0.03921907,  0.65326383,  0.79779432],
       [ 0.9505454 ,  0.5496442 ,  0.04995717]])

In [42]:
p = np.zeros(z.shape)

In [43]:
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
z = np.array([_ for _ in range(16)]).reshape(4,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
z*z

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [49]:
eps = 1e-8

In [50]:
np.sqrt(z)+eps

array([[1.00000000e-08, 1.00000001e+00, 1.41421357e+00, 1.73205082e+00],
       [2.00000001e+00, 2.23606799e+00, 2.44948975e+00, 2.64575132e+00],
       [2.82842713e+00, 3.00000001e+00, 3.16227767e+00, 3.31662480e+00],
       [3.46410163e+00, 3.60555129e+00, 3.74165740e+00, 3.87298336e+00]])

In [53]:
func = lambda x,y : x**2 + y

In [57]:
func(4,1)

17